export const details=[
    {
      id:"1",  
      name:"James",
      profession:"Student",
      distance:"1.3",
      match:"80",
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"

    },
    {
        name:"James",
        id:"2",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"3",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"4",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"5",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"6",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"7",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"8",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      },
      {
        name:"James",
        id:"9",
        profession:"Student",
        distance:"1.3",
        match:"80",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&s"
      }
]